backend:
  name: git-gateway
  branch: netlify-cms # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "news" # Used in routes, e.g. /admin/collections/blog
    label: "News" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "home"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Intro Title, name: intro-title, widget: string}
          - {label: Intro Subtitle, name: intro-subtitle, widget: string}
          - {label: Intro Body, name: intro-body, widget: markdown}
          - {label: Intro Image, name: intro-img, widget: image}
          - {label: Feature Title, name: feature-title, widget: string}
          - {label: Feature Subtitle, name: feature-subtitle, widget: string}
          - {label: Feature Body, name: feature-body, widget: markdown}
          - {label: Feature Image, name: feature-img, widget: image}
          - {label: Testimonial Title, name: testimonial-title, widget: string}
          - {label: Testimonial Subtitle, name: testimonial-subtitle, widget: string}
          - {label: Hotels, name: hotels, widget: number}
          - {label: Resturants, name: resturants, widget: number}
          - {label: Museums, name: museums, widget: number}
          - {label: Minutes, name: minutes, widget: number}
          - {label: Services Title, name: services-title, widget: string}
          - {label: Services Subtitle, name: services-subtitle, widget: string}

      - label: "Contact"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: string}
          - {label: Icon, name: icon, widget: string}
          # - {label: Intro, name: intro, widget: markdown}
          # - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
          # - {label: "Subtitle", name: "subtitle", widget: "string"}
          # - {label: "Visitors Text", name: "visitorstext", widget: "markdown"}